name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: sudo apt install -y nasm cargo
      
    - name: Configure apps
      run: rustup update && rustup default nightly
    
    - name: Build ISO file
      run: make build-linux
