name: Build Disk Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: sudo apt install -y nasm cargo
      
    - name: Configure rust
      run: rustup update && rustup default nightly && rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      
    - name: Compile Rust
      run: cargo rustc -Z build-std=core --target x86_baremetal.json -- --emit obj=../kernel.o
      working-directory: ./Kernel
    
    - name: Link Rust
      run: ld -m elf_i386 -T linker.ld -nostdlib --nmagic -o kernel.elf kernel.o
      
    - name: Compile Assembly
      run: make asm
    
    - name: Link bootloader and kernel
      run: mkdir -p iso && ld -m elf_i386 boot.elf kernel.elf -o iso/main.img
      
    - name: Create ISO disk image
      run: genisoimage -quiet -no-emul-boot -V 'BOOT' -input-charset iso8859-1 -o ./out/boot.iso -b main.img -hide main.img iso/
